src/main/java/com/eprosima/idl/context/Context.java

When using the generator from a path that is not a parent of the file name, the absolute path prefix "/" gets removed on Linux in processPreprocessorLine for scoped files. In custom code, it now assumes a relative path instead of a full path and thus I cannot find the file.

Don't remove prefixed "/" on absolute paths

---

src/main/antlr4/omg/com/eprosima/idl/parser/grammar/IDL.g4
src/main/java/com/eprosima/idl/context/Context.java

Fixes eProsima/Fast-RTPS#360
Forbids the usage if keywords as identifiers ignoring case.
Adds escape character to allow use keywords as identifiers.

Feature/name collision [5008]

---

src/main/antlr4/omg/com/eprosima/idl/parser/grammar/IDL.g4
src/main/java/com/eprosima/idl/context/Context.java

Though a sentence in section 7.2.6.3 indicates that there is another alternative to single super long lines: "Adjacent string literals are concatenated."

Refs #6299 Added string literal concatenation feature [6323]

---

src/it/java/com/eprosima/integration/Command.java

This PR fixes a deadlock caused by not consuming output from the executed command, discovered at https://github.com/eProsima/Fast-RTPS-Gen/issues/4#issuecomment-536613903
More details about the issue:
https://stackoverflow.com/questions/5483830/process-waitfor-never-returns

Refs #6488 Fix deadlock while waiting for command. [6491]

---

src/main/java/com/eprosima/idl/parser/tree/TreeNode.java
src/main/java/com/eprosima/idl/parser/typecode/AliasTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java

Composes the fix of https://github.com/eProsima/Fast-RTPS-Gen/issues/19.
In this case, it allows to generate a scope that is compatible with the ROS2 naming.
@LuisGP @richiware for your review and acceptance.

parser: add 'getROS2Scopedname' method to return a type name compatible with ROS2

---

src/main/java/com/eprosima/idl/parser/typecode/UnionTypeCode.java

Just what the title says. Unions should not be marked as plain, as their CDR serialization may not be equal to their in-memory representation.

Mark unions as not plain

---

src/main/java/com/eprosima/idl/parser/typecode/TypeCode.java

Fast DDS Gen is generating wrong TypeObject registration code for types containing arrays or sequences of `long double`.
This PR helps reducing boilerplate code for converting `long double` into `longdouble`, as required by `get_xxx_identifier` calls

[13986] Add convenience method getCppTypenameForTypeId

---

pom.xml

This PR updates the path in `pom.xml` to reflect the new location of the `IDL.g4` grammar file.

Fix grammar path in pom.xml

---

src/main/java/com/eprosima/idl/parser/typecode/SequenceTypeCode.java

#57 introduced a regression by which bounded sequences where considered unbounded. This is specially problematic when leveraging Fast DDS Data Sharing delivery mechanism as, because of #57, bounded sequences could not be used. This PR fixes that regression so that bounded sequences are indeed considered bounded

[15294] Fix isIsBounded for sequences

---

src/main/java/com/eprosima/idl/parser/typecode/BitmaskTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java

Currently, the `@bit_bound` seems to be applied after the `@position` calculation for members of a bitmask. This PR introduces a filter that removes all out-of-bounds members after the bit_bound update.

[17352] Added post-creation filter for out of bounds positions

---

src/main/resources/com/eprosima/idl/templates/CTypes.stg

Fix for https://github.com/eProsima/Micro-XRCE-DDS-Gen/issues/54
Tiny integer types were missing on CTypes template.

Add int8 and uint8t to CTypes template

---

src/main/java/com/eprosima/idl/parser/exception/RuntimeGenerationException.java
src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/TypeCode.java

Only a MemberedTypeCode is plain if the extensibility is final.
Also added exception RuntimeGenerationException.
Also added TypeCode.default_extensibility

Fix returning is_plain [19541]

---

src/main/antlr/com/eprosima/idl/parser/grammar/IDL.g4
src/main/java/com/eprosima/idl/context/Context.java
src/main/java/com/eprosima/idl/parser/typecode/ArrayTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/MapTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/SequenceTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/SetTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/StringTypeCode.java

Fixed bug when using const as literals.
Reported in https://github.com/eProsima/Fast-DDS-Gen/issues/55
Found aditional problems with wchar and wstring literals.

[19668] Fixed bug when using const as literals.

---

.github/dco.yml
.github/workflows/mirror.yml
build.gradle
pom.xml

This PR:
1. Bumps project version to 2.0.0
2. Adds a mirror workflow so that the latest version branch is kept up to date with master.
This is necessary to transition to a branching model similar to Fast DDS', where master is kept as a development branch, and each minor version has a corresponding X.Y.x branch so we can handle backports and releases in a more consistent manner.
3. Adds a dco.yml so that GPG signed commits automatically pass the DCO

[19897] Bump version to 2.0.0

---

src/main/antlr/com/eprosima/idl/parser/grammar/IDL.g4
src/main/java/com/eprosima/idl/context/Context.java
src/main/java/com/eprosima/idl/generator/manager/TemplateManager.java
src/main/java/com/eprosima/idl/test/TestIDLParser.java

This PR contains:
- `Context` contains a new function `createModule()` which can be override.
- Now `Context` `addModule()` function is the responsible of calling `module` template and setting the current scope.
- Moved the loading of templates related about Types from `TemplateManager` to `Context`.
- Now `Context` constructor expects an instance of `TemplateManager`.

Several changes to support fastddsgen -genapi [19957]

---

src/main/java/com/eprosima/idl/parser/tree/Annotation.java
src/main/java/com/eprosima/idl/parser/tree/AnnotationMember.java
src/main/java/com/eprosima/idl/parser/typecode/AliasTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/MapTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/PrimitiveTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/SequenceTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/StringTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/TypeCode.java

This PR complements and extends #103.

[19595] Fix API for TypeObject code generation

---

src/main/antlr/com/eprosima/idl/parser/grammar/IDL.g4
src/main/java/com/eprosima/idl/parser/typecode/UnionTypeCode.java

Fix the union member_ids to account for the fact that the discriminator should always have the ID 0.

Fixed member_id for unions.

---

src/main/antlr/com/eprosima/idl/parser/grammar/IDL.g4
src/main/java/com/eprosima/idl/context/Context.java

Currently the parser fails if it encounters a oneway operation. This PR fixes it.
- *N/A* Changes are API compatible. 
- _N/A_ Check CI results: changes do not issue any warning.
- _N/A_ Check CI results: failing tests are unrelated with the changes.

Fix parsing IDL oneway operations [21145]

---

src/main/java/com/eprosima/idl/parser/typecode/BitfieldSpec.java

Fix default enclosing type for 1-byte bitfield: TK_UINT8 instead of TK_BYTE.

Fix default enclosing type for 1-byte bitfield [21264]

---

src/main/antlr/com/eprosima/idl/parser/grammar/IDL.g4
src/main/java/com/eprosima/idl/generator/manager/TemplateUtil.java
src/main/java/com/eprosima/idl/parser/typecode/UnionTypeCode.java

This PR adds annotations for union's discriminator in the grammar. Also it adds the `@default` annotation for union's discriminator in the library. And it changes how to calculate the discriminator's value for default case in primitive types: instead of searching for the lower value, it searches the greater one.

Annotations for union's discriminators [21236]

---

src/main/java/com/eprosima/idl/parser/typecode/UnionTypeCode.java

This PR enables the use of any `@default` annotation value for unions.
Required by:
* eProsima/Fast-DDS#5081
Depends on:
*eProsima/dds-types-test#34

[21313] Allow all @default annotation values for unions

---

src/main/antlr/com/eprosima/idl/parser/grammar/IDL.g4
src/main/java/com/eprosima/idl/context/Context.java
src/main/java/com/eprosima/idl/parser/tree/ConstDeclaration.java

Fixes #150.
- ❌ Changes are API compatible. 

 [21346] Fix generation for new kind of constants

---

src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java

This PR implements a new function `getMemberById` for being used in STG.
- _N/A_: Check CI results: changes do not issue any warning.
- _N/A_:  Check CI results: failing tests are unrelated with the changes.

[21391] Add new function getMembersById for STG

---

src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java

This PR applies a suggestion: check `@key`  annotation is not used in a structure's member of a derived structure.

[21430] Add check not using @key in derived structures

---

src/main/java/com/eprosima/idl/parser/typecode/UnionTypeCode.java

For unions with boolean or enumeration discriminator if all cases are covered, the default discriminator value is set correctly to `true` or to first enumeration literal but the C++ constructor not initialize that member.

[21595] Unions with Boolean or Enumeration discriminator might not be initialized correctly

---

src/main/java/com/eprosima/idl/parser/typecode/TypeCode.java

This PR removes a function which wouldn't exists because it doesn't follow the mechanism to calculate extensibility.
- *N/A* Changes are API compatible. 

[21604] Remove function can lead to error

---

src/main/java/com/eprosima/idl/parser/typecode/TypeCode.java

Currently IDL-Parser returns the typename `uint8_t` for TK_UINT8 and TK_BYTE. This provokes Fast-DDS-Gen generates the same typename for collections of this primitive types. This PR fixes it.

[21685] Use different typename for TK_UINT8 and TK_BYTE

---

build.gradle
pom.xml

Thiss PR bumps IDL Parser version to v4.0.2
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- **N/A** Any new/modified methods have been properly documented.
- **N/A** Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- **N/A** Changes are API compatible. 
- **N/A** Applicable backports have been included in the description.

[21783] Bump version to v4.0.2

---

src/main/java/com/eprosima/idl/parser/tree/Exception.java
src/main/java/com/eprosima/idl/parser/tree/Operation.java
src/main/java/com/eprosima/idl/parser/tree/TreeNode.java
src/main/java/com/eprosima/idl/parser/tree/TypeDeclaration.java
src/main/java/com/eprosima/idl/parser/typecode/AliasTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/AnyTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/BitfieldSpec.java
src/main/java/com/eprosima/idl/parser/typecode/ContainerTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/PrimitiveTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/StringTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/TypeCode.java

* Add `isAnnotatedAsNested` method to `TreeNode` so we can check for `@nested` annotation in the templates
* Add `getNamespace` method to `TreeNode` and `TypeCode` to help templates distinguish between `scope` and `namespace` for declarations inside interfaces
* Add `isDeclaredInsideInterface` method to `TypeCode` so we can check whether a type has been declared inside an interface in the templates.
- https://github.com/eProsima/dds-types-test/pull/43

[23153] Improvements for `interface` and `@nested`

---

src/main/java/com/eprosima/idl/parser/tree/TreeNode.java
src/main/java/com/eprosima/idl/parser/typecode/AliasTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java
src/main/java/com/eprosima/idl/parser/typecode/TypeCode.java

This adds some methods to disambiguate the name of type object registration methods of types declared with the same name inside and outside an interface.
- **NO**: Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 

[23268] Methods for type object registration of types declared inside interfaces
