.gitignore, src/main/java/com/eprosima/idl/context/Context.java, src/main/java/com/eprosima/idl/parser/tree/AnnotationMember.java, src/main/java/com/eprosima/idl/parser/tree/Interface.java, src/main/java/com/eprosima/idl/parser/tree/Module.java, src/main/java/com/eprosima/idl/parser/tree/TreeNode.java, src/main/java/com/eprosima/idl/parser/typecode/ArrayTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/ContainerTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/Member.java, src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/SequenceTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/StringTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/StructTypeCode.java, src/main/java/com/eprosima/idl/templates/CTypes.stg
Necessary changes to adapt Micrortpsgen with strings, sequences and arrays.
=> Improve support of complex C types

src/main/java/com/eprosima/idl/parser/typecode/SequenceTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/StringTypeCode.java
Changed values between string default size and sequence default size.
Now: string: 255, sequence: 100.
=> bugfix/Fix default string and sequences sizes.

idl.gradle
=> update source and target to java 7

src/main/java/com/eprosima/idl/context/Context.java, src/main/java/com/eprosima/idl/util/Util.java
=> Refs #5355 Fixes situation where include directory may be simplified …[5629]

idl.gradle, kiara.gradle, pom.xml, src/main/java/com/eprosima/idl/generator/manager/TemplateUtil.java
This PR:
* Sets compatibility with java 1.8 and antlr 4.5
* Uses gradle builtin antlr plugin instead of the community one
* Fixes warnings
=> Using java 1.8

idl.gradle
This should fix issue eProsima/Fast-RTPS#583
=> Refs #5877. Back to old antlr4 gradle plugin.

src/main/java/com/eprosima/idl/context/Context.java
=> Refs #6318 Annotations name collision only must be performed against … [6324]

src/main/java/com/eprosima/idl/parser/typecode/ContainerTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/MapTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/Member.java, src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/SequenceTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/SetTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/StringTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/StructTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/TypeCode.java
- A type is plain if doesn't need a size on serialization
- A type is bounded if its maximum size is known.
=> Refs #9038 Added isIsPlain and isIsBounded methods. [9051]

src/main/antlr4/omg/com/eprosima/idl/parser/grammar/IDL.g4
=> Fixes Object keyword not being considered to be an escaped type name.

idl.gradle, pom.xml
Signed-off-by: Eduardo Ponz <eduardoponz@eprosima.com>
=> Bump version to v1.1.2 [13785]

idl.gradle, pom.xml
Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>
=> [14124] Bump version to v1.2.0

src/main/java/com/eprosima/idl/parser/typecode/StringTypeCode.java, src/main/resources/com/eprosima/idl/templates/Types.stg
Signed-off-by: Miguel Company <MiguelCompany@eprosima.com>
=> [14669] Use special cppType for bounded strings

idl.gradle, pom.xml
Signed-off-by: Miguel Company <MiguelCompany@eprosima.com>
=> [14910] Bump version to v1.3.0

build.gradle, pom.xml
Signed-off-by: Eduardo Ponz <eduardoponz@eprosima.com>
=> [15600] Bump version to v1.4.0

build.gradle, pom.xml
Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>
=> [16440] Bump version to v1.5.0

src/main/java/com/eprosima/idl/context/Context.java
=> Wrong order of types registration in generated TypeObject [18204]

src/it/java/com/eprosima/integration/IDL.java, test/idls/inheritance.idl
Regression test for eprosima/fast-dds-gen#156
=> Regression test [17526]

build.gradle, kiara.gradle, pom.xml
There are no unit tests.
Also note pom.xml and the gradle files reference different versions of JUnit.
=> Remove unused JUnit

src/main/java/com/eprosima/idl/context/Context.java, src/main/java/com/eprosima/idl/test/TestIDLParser.java, src/main/java/com/eprosima/solution/Project.java
This function could be used by source code generators to get the relative directory from the current processed IDL file.
=> Add new Context.getRelativeDir function [19081]

src/it/java/com/eprosima/integration/Test.java, src/main/antlr/com/eprosima/idl/parser/grammar/IDL.g4, src/main/java/com/eprosima/idl/parser/typecode/Member.java, src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/StructTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/UnionTypeCode.java
Depends on:
- eprosima/fast-cdr#170
=> Extra functionality for support external members [19710]

src/main/antlr/com/eprosima/idl/parser/grammar/IDL.g4, src/main/java/com/eprosima/idl/parser/tree/ConstDeclaration.java
This PR includes new TemplateGroups to generate code related to collections (sequences, maps and arrays) and strings/wstrings.
=> [19671] Collection templates

src/main/antlr/com/eprosima/idl/parser/grammar/IDL.g4, src/main/java/com/eprosima/idl/parser/tree/Inherits.java, src/main/java/com/eprosima/idl/parser/typecode/BitsetTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/StructTypeCode.java
XTypes v1.3 Clause 7.2.2.4.5
> The Type System supports single inheritance of Aggegated [sic] Types.
IDL v1.4 Clause 7.4.13.4
> Additions to structure definition in order to support single inheritance and void content (no members).
=> [19791] Type system only supports single inheritance

src/it/java/com/eprosima/integration/Test.java, src/it/java/com/eprosima/integration/TestManager.java, src/main/java/com/eprosima/idl/parser/typecode/ArrayTypeCode.java
- Support testing several fastcdr versions
- Support a blacklist for tests
=> Improve testing [19872]

src/main/antlr/com/eprosima/idl/parser/grammar/IDL.g4, src/main/antlr4/kiara/com/eprosima/idl/parser/grammar/KIARAIDL.g4, src/main/java/com/eprosima/idl/generator/manager/TemplateUtil.java, src/main/java/com/eprosima/idl/parser/typecode/UnionTypeCode.java, src/main/java/com/eprosima/idl/test/TestIDLParser.java
Union discriminator should be of UnionMember type and not directly TypeCode.
=> [19932] Fix union discriminator

src/main/java/com/eprosima/idl/context/Context.java, src/main/java/com/eprosima/idl/generator/manager/TemplateGroup.java, src/main/java/com/eprosima/idl/generator/manager/TemplateManager.java, src/main/java/com/eprosima/idl/generator/manager/TemplateST.java, src/main/java/com/eprosima/idl/generator/manager/TemplateSTGroup.java, src/main/java/com/eprosima/idl/parser/typecode/AliasTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/TypeCode.java
Provides new functionality: support to have configuration by STGroup (included in new class TemplateSTGroup) and avaiable in each STG file through `Context.get_template_manager().get_current_template_stgroup()`.
=> Support to have configuration by STGroup [19995]

src/main/antlr/com/eprosima/idl/parser/grammar/IDL.g4, src/main/java/com/eprosima/idl/parser/tree/Inherits.java, src/main/java/com/eprosima/idl/parser/typecode/AliasTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/BitsetTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/StructTypeCode.java
This PR fixes an inheritance from an alias is not generated.
=> Fixing inheritance with aliases [20620]

src/main/java/com/eprosima/idl/parser/typecode/EnumTypeCode.java
This PR fixes the getters of Enum for bounded and plain
=> Fix Enum plain and bounded getters

build.gradle, pom.xml
This PR bumps the project version to 1.6.1
=> [20741] Bump version to 1.6.1

src/main/java/com/eprosima/idl/context/Context.java
This PR introduces improvements regarding path processing:
* Path normalization
* Replace '\' with '/' in dependencies
=> [20755] Improve path processing 

src/main/java/com/eprosima/idl/context/Context.java
This PR: NormalizeS path and substituteS backslash with slash in Contex.java
=> [20755] Improve path processing

.github/pull_request_template.md, .github/workflows/mirror.yml
This PR prepares the 4.0.x-devel branch to become master.
=> [20893] Prepare 4.0.x-devel to become master

.github/workflows/mirror.yml
This PR adds a mirror workflow to 1.7.x.
=> [20893] Add mirror job

src/main/java/com/eprosima/idl/parser/tree/Annotation.java
This PR adds API to Annotation class to access the AnnotationDeclaration.
=> [20853] API to access AnnotationDeclaration

src/main/antlr/com/eprosima/idl/parser/grammar/IDL.g4, src/main/java/com/eprosima/idl/parser/typecode/AliasTypeCode.java, src/main/java/com/eprosima/idl/parser/typecode/Bitfield.java, src/main/java/com/eprosima/idl/parser/typecode/BitsetTypeCode.java, src/main/java/com/eprosima/idl/test/TestIDLParser.java
Generate bitsets according to standard IDL to C++11 2021.
Depends on:
- #135
=> Bitsets according to standard IDL to C++11 2021 [21027]

.github/pull_request_template.md, RELEASE_SUPPORT.md
This PR adds the `RELEASE_SUPPORT.md` to `IDL-parser` repo in order to comply with our branching model.
@Mergifyio backport 3.0.x 1.5.x 1.2.x
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- **N/A** Any new/modified methods have been properly documented.
- **N/A** Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- **N/A** Changes are API compatible.
=> [20946] Add RELEASE_SUPPORT.md and update PR template versions

build.gradle, pom.xml
This PR bump to v4.0.0
- N/A Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- N/A Any new/modified methods have been properly documented.
- N/A Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- N/A Changes are API compatible. 
- N/A Applicable backports have been included in the description.
=> [21366] Bump to v4.0.0

build.gradle, pom.xml
This  PR bumps the IDL-Parser version to v4.0.1
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- **N/A** Any new/modified methods have been properly documented.
- **N/A** Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- **N/A** Changes are API compatible. 
- **N/A** Applicable backports have been included in the description.
=> [21636] Bump version to v4.0.1

src/main/java/com/eprosima/idl/generator/manager/TemplateGroup.java
When generating code from STG files, currently blank lines are inserted. This PR avoids this.
=> [21925] Avoid render blank lines

build.gradle, pom.xml
This PR bumps the version to 4.0.3
=> [21832] Bump version to 4.0.3

.github/workflows/mirror.yml, build.gradle, pom.xml
This makes the master branch be 4.1.x, in preparation for the next minor release 4.1.0
=> [22797] Branchout 4.1.0

src/main/antlr/com/eprosima/idl/parser/grammar/IDL.g4, src/main/java/com/eprosima/idl/parser/tree/Param.java
This adds support for annotations to interface operation parameters
=> [22764] Support annotations on operation parameters

src/main/java/com/eprosima/idl/parser/tree/Exception.java
This PR makes exception members have a consistent index attribute.
@Mergifyio backport 4.0.x
=> [22768] Set index on exception members

build.gradle, pom.xml
This PR bumps the project version to v4.0.4
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- **N/A** Any new/modified methods have been properly documented.
- **N/A** Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- **N/A** Changes are API compatible. 
- **N/A** Applicable backports have been included in the description.
=> [22858] Bump version to 4.0.4

RELEASE_SUPPORT.md
This PR adds latest version of Fast DDS Gen and also includes EOL versions
- _N/A_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- _N/A_ Any new/modified methods have been properly documented.
- _N/A_ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- _N/A_ Changes are API compatible. 
- _N/A_ Applicable backports have been included in the description.
=> [21427] Add v4.0.4 & EOL versions to Release Support

.github/pull_request_template.md, RELEASE_SUPPORT.md
=> [23520] Prepare for v4.2.0
